print "<!DOCTYPE html>\n";
print "<html>\n";
print "    <head>\n";
print "        <title>Plant A Tree</title>\n";
print "        <meta name=\"description\" content=\"This is the description\">\n";
print "        <link rel=\"stylesheet\" href=\"styles.css\" />\n";
print "    </head>\n";
print "    <body>\n";
print "        <header class=\"main-header\">\n";
print "            <nav class=\"nav main-nav\">\n";
print "                <ul>\n";
print "                    <li><a href=\"index.html\">HOME</a></li>\n";
print "                     <li><a href=\"category.html\">CATEGORY</a></li>\n";
print "                    <li><a href=\"about.html\">ABOUT</a></li>\n";
print "                </ul>\n";
print "            </nav>\n";
print "\n";
print "            <h1 class=\"band-name band-name-large\">TreeCo</h1>\n";
print "						</header>\n";
print "            <section class=\"content-section container\">\n";
print "            <h2 class=\"section-header\">HOME</h2>\n";
print "            \n";
print "            <form>\n";
print "	            <label>User Name:  <input type=\"text\" name=\"namefield\"></label>\n";
print "	            <label><br>Password:  <input type=\"text\" name=\"pwdfield\"></label><br><br>\n";
print "	            <p><a href=\"category.html\"> Login</a></br></p>\n";
print "	            <p><a href=\"addUser.php\"> Sign Up</a></br></p>\n";
print "	            <p><a href=\"category.html\"> Continue Without Login</a></br></p>\n";
print "            </form>\n";
print "            \n";
print "            </section>\n";
print "      \n";
print "     <footer class=\"main-footer\">\n";
print "        <div class=\"container main-footer-container\">\n";
print "            <h3 class=\"band-name\">TreeCo</h3>\n";
print "        </div>\n";
print "    </footer>\n";
print "</body>\n";
print "</html>";